version: '3.1'

services:

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "./docker/.postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  rails:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
    depends_on:
      - postgres
    command: rails server -e production -b 0.0.0.0

  delayed_job:
    build: .
    restart: always
    depends_on:
      - postgres
      - rails
    command: bundle exec rake jobs:work
