version: '3.1'

services:

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: rides_development
    volumes:
      - "./docker/.postgres:/var/lib/postgresql/data"
    # user: 1000:1000
    ports:
      - "5432:5432"
  rails:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: rails server -e production -b 0.0.0.0

  delayed_job:
    build: .
    restart: always
    depends_on:
      - postgres
      - rails
    command: bundle exec rake jobs:work
